### ISSUE TITLE
Project progress

### ISSUE THREAD

**Issue by vidya88** [SkycoinProject/ledger-nano#3]
@Retsediv commented on Feb 4

**Feature description**
Basic functional for BOLOS app

**Describe the solution you'd like**
The main high-level tasks: generate keypair, sign a transaction and send it back to the desktop companion app, simple user interface(like in similar apps)

**Possible implementation:**

- [x]  Initialize repo and whole workflow [#2](https://github.com/skycoin/ledger-nano/issues/2)
- [x]  App description, version, menu [#9](https://github.com/skycoin/ledger-nano/issues/9)
- [x]  Public/private keys generation [#4](https://github.com/skycoin/ledger-nano/issues/4)
- [x]  Creating the signature for transaction [#10](https://github.com/skycoin/ledger-nano/issues/10)
- [x]  Key derivation
- [x]  Text display
- [ ]  Wrapper [#21](https://github.com/skycoin/ledger-nano/issues/21)
- [ ]  Tests [#20](https://github.com/skycoin/ledger-nano/issues/20)
- [ ]  Interaction with companion app
- [ ]  Check for vulnerabilities
